import os
import h5py
import numpy as np
from tqdm import tqdm
import cv2

"""
This script performs focus stacking on each tile in every H5 image in the dataset.
For each tile, it computes the Laplacian of Gaussian (LoG) for each depth slice,
then collapses the stack by selecting, for each pixel, the value from the slice with the 
highest LoG response.The resulting 2D image is saved in a new field in the tile group, 
and metadata is updated.
"""

def laplacian_of_gaussian(gray, k=5):
    """
    Compute Laplacian of Gaussian for a 2D image.
    
    Args:
        gray: 2D numpy array (grayscale image)
        k: kernel size for Gaussian blur (should be odd)

    Returns:
        2D numpy array of the same shape as input, containing the LoG response
    """
    blurred = cv2.GaussianBlur(gray, (k, k), 0)
    return cv2.Laplacian(blurred, cv2.CV_64F, ksize=k)

def focus_stack(tile, k=5):
    """
    Focus stack a tile of shape (w, h, c, z) to (w, h, c). 
    Applies focus stacking per channel.

    Args:
        tile: 4D numpy array of shape (w, h, c, z)
    
    Returns:
        stacked: 3D numpy array of shape (w, h, c) after focus stacking
        avg_vols: 1D numpy array of average VoL per focal plane (z)
    """
    z_axis = tile.ndim - 1
    tile_zfirst = np.moveaxis(tile, z_axis, 0)  # (z, w, h, c)
    z, w, h, c = tile_zfirst.shape

    # Convert each z-slice to grayscale for focus measure
    gray_stack = np.zeros((z, w, h), dtype=np.float32)
    for zi in range(z):
        img = tile_zfirst[zi].astype(np.uint8) if tile_zfirst[zi].dtype != np.uint8 else tile_zfirst[zi]
        gray_stack[zi] = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

    # Compute LoG for each grayscale z-slice
    log_stack = np.array([laplacian_of_gaussian(gray_stack[zi], k) for zi in range(z)])
    log_abs = np.abs(log_stack)
    avg_logs = log_abs.mean(axis=(1,2))

    # For each pixel, select the z with the highest LoG response
    best_z = np.argmax(log_abs, axis=0)  # shape (w, h)

    # Use best_z to select the pixel from each channel
    stacked = np.zeros((w, h, c), dtype=tile.dtype)
    for ch in range(c):
        channel_stack = tile_zfirst[..., ch]  # (z, w, h)
        # Use advanced indexing to select the best z for each pixel
        stacked[..., ch] = channel_stack[best_z, np.arange(w)[:, None], np.arange(h)]

    return stacked, avg_logs


def best_focal_plane(tile, k=5):
    """
    Select the single sharpest focal plane from a tile stack.

    Args:
        tile: 4D numpy array of shape (w, h, c, z)
        k: kernel size for Gaussian blur used in LoG focus metric

    Returns:
        best_plane: 3D numpy array of shape (w, h, c)
        best_z: integer index of the selected z-plane
    """
    z_axis = tile.ndim - 1
    tile_zfirst = np.moveaxis(tile, z_axis, 0)  # (z, w, h, c)
    z, w, h, _ = tile_zfirst.shape

    gray_stack = np.zeros((z, w, h), dtype=np.float32)
    for zi in range(z):
        img = tile_zfirst[zi].astype(np.uint8) if tile_zfirst[zi].dtype != np.uint8 else tile_zfirst[zi]
        gray_stack[zi] = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

    log_stack = np.array([laplacian_of_gaussian(gray_stack[zi], k) for zi in range(z)])
    avg_logs = np.abs(log_stack).mean(axis=(1, 2))
    best_z = int(np.argmax(avg_logs))
    return tile_zfirst[best_z], best_z

def process_h5_file(h5_path: str):
    """
    Loop through an H5 file as generated by generate_tiles.py,
    perform focus stacking on each tile, and save results.
    
    Args:
        h5_path: Path to the H5 file to process
    """

    with h5py.File(h5_path, 'r+') as h5f:

        print(f"Processing {h5_path.split('/')[-1]} with {len(h5f.keys())} tiles...")

        # Loop through each tile in the H5 file
        for tile_name in tqdm(h5f.keys()):
            
            group = h5f[tile_name]
            
            # Ensure group is an h5py.Group and contains 'data' dataset
            if not isinstance(group, h5py.Group) or 'data' not in group.keys():
                continue
            data = group['data'][:]
            
            # Focus stack and get average LoG per slice
            stacked, avg_logs = focus_stack(data)

            # Get focal plane ranking based on average LoG (descending order)
            ranking = np.argsort(avg_logs)[::-1]  # descending order

            # Save the ranking
            if 'focal_plane_ranking' in group.keys():
                del group['focal_plane_ranking']
            group.create_dataset('focal_plane_ranking', data=ranking, compression='gzip')

            # Save the stacked image
            if 'focus_stacked' in group.keys():
                del group['focus_stacked']
            group.create_dataset('focus_stacked', data=stacked, compression='gzip')

if __name__ == "__main__":
    
    INPUT_DIR = "/path/to/h5/files"
    for fname in os.listdir(INPUT_DIR):
        if fname.endswith('.h5'):
            process_h5_file(os.path.join(INPUT_DIR, fname))