import os
import h5py
import numpy as np
from tqdm import tqdm

"""
This script performs Maximum Intensity Projection (MIP) on each tile in every H5 image in the dataset.
For each tile, it collapses the z-stack by selecting, for each pixel, the maximum intensity value 
across all z slices. The resulting 2D image is saved in a new field in the tile group, and metadata 
is updated.
"""

def maximum_intensity_projection(tile):
    """
    Perform maximum intensity projection on a tile of shape (w, h, c, z) to (w, h, c).
    Args:
        tile: 4D numpy array of shape (w, h, c, z)
    Returns:
        mip: 3D numpy array of shape (w, h, c) after MIP
    """
    z_axis = tile.ndim - 1
    mip = np.max(tile, axis=z_axis)
    return mip

def process_h5_file(h5_path):
    """
    Loop through an H5 file as generated by generate_tiles.py,
    perform MIP on each tile, and save results.
    Args:
        h5_path: Path to the H5 file to process
    """
    with h5py.File(h5_path, 'r+') as h5f:

        print(f"Processing {h5_path} with {len(h5f.keys())} tiles...")

        # Loop through each tile in the H5 file
        for tile_name in tqdm(h5f.keys()):

            group = h5f[tile_name]

            # Ensure group is an h5py.Group and contains 'data' dataset
            if not isinstance(group, h5py.Group) or 'data' not in group.keys():
                continue
            data = group['data'][:]
           
            # Perform maximum intensity projection
            mip = maximum_intensity_projection(data)

            # Save the projected image
            if 'maximum_intensity_projection' in group.keys():
                del group['maximum_intensity_projection']
            group.create_dataset('maximum_intensity_projection', data=mip, compression='gzip')

if __name__ == "__main__":

    INPUT_DIR = "/path/to/h5/files"
    for fname in os.listdir(INPUT_DIR):
        if fname.endswith('.h5'):
            process_h5_file(os.path.join(INPUT_DIR, fname))
