import os
import random
import h5py
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches

"""
This test script reads a sample H5 file generated by generate_tiles.py, 
prints out the image-level and tile-level metadata, and 
visualizes a few tiles with their annotations.

Make sure to update the H5_DIR variable to point to the directory 
containing your H5 files.
"""

# Path to the directory containing H5 files
H5_DIR = "/path/to/h5/files"  # Update with actual path to H5 files

# Find an H5 file in the directory
h5_files = [f for f in os.listdir(H5_DIR) if f.endswith(".h5")]
if not h5_files:
    raise FileNotFoundError(f"No H5 files found in {H5_DIR}")
h5_path = os.path.join(H5_DIR, h5_files[20])

with h5py.File(h5_path, "r") as h5f:
    print("Image-level metadata:")
    for k, v in h5f.attrs.items():
        print(f"  {k}: {v}")

    tile_keys = list(h5f.keys())
    if len(tile_keys) < 10:
        chosen_tiles = tile_keys
    else:
        chosen_tiles = random.sample(tile_keys, 10)

    for idx, tile_key in enumerate(chosen_tiles):
        group = h5f[tile_key]
        image = group["data"][:]
        bboxes = group["bboxes"][:]
        labels = group["labels"][:]
        # Print tile-level metadata
        print(f"\nTile {tile_key}:")
        for attr in group.attrs:
            print(f"  {attr}: {group.attrs[attr]}")

        # Assume image shape is (H, W, C) or (H, W, C, Z), take first Z if needed
        print(image.shape)
        image = image[..., 12]  # Take 12th z-stack
        img_disp = image.astype(np.uint8)

        fig, ax = plt.subplots(1)
        ax.imshow(img_disp)
        for bbox, label in zip(bboxes, labels):
            x, y, w, h = bbox
            rect = patches.Rectangle((x, y), w, h, linewidth=2, edgecolor='r', facecolor='none')
            ax.add_patch(rect)
            ax.text(x, y, str(label), color='yellow', fontsize=10, bbox=dict(facecolor='black', alpha=0.5))
        ax.axis('off')
        plt.savefig(os.path.join("output", f"tile_{idx}_{tile_key}.png"), bbox_inches='tight')
        plt.close()